### ISSUE TITLE
Remove Legacy Properties Option

### ISSUE THREAD

**Issue by dmosorast** [singer-io/singer-tap-template#4]
The template differentiates between `properties` and `catalog` and will accept both. However, the `--properties` argument is deprecated in the Singer spec, and if it's passed in, then taps written with this template expecting the catalog will not function.

I would like to propose removing the properties argument handling [here](https://github.com/singer-io/singer-tap-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/%7B%7Bcookiecutter.package_name%7D%7D/__init__.py#L93-L94) since all new taps should conform to the latest standards.

**Comment by zenkay** [comment]
Hi @dmosorast! I suppose that #5 close this issue. Is that right? I'm going to start developing a tap and I was checking the issues first 😉

**Comment by dmosorast** [comment]
@zenkay You are correct! I guess this got overlooked when that was merged. Thanks for letting me know! Closing this one.
